name: kaleidoscope
channels:
  - rdkit
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=2.0.3
  - boto3=1.28.45
  - transformers=4.32.1
  - pytorch=2.0.1+cpu
  - networkx=3.1
  - scikit-learn=1.3.0
  - pyyaml=6.0.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - rdkit=2023.03.2
  - pip
  - pip:
      - 'git+https://github.com/your-repo/any-additional-pip-packages.git'