# config/quantum_config.yml
system:
  n_workers: 4  # Number of parallel workers for processing
  temp_dir: "/tmp/quantum_system"
  process_timeout: 300  # seconds

molecular_processing:
  force_field: "MMFF94"
  optimization_steps: 1000
  convergence_threshold: 1e-6
  energy_unit: "kJ/mol"

performance:
  max_memory_percent: 80  # Maximum memory usage threshold
  max_cpu_percent: 90    # Maximum CPU usage threshold
  chunk_size: 1000       # Size of data chunks for processing

graph_analysis:
  n_clusters: 3
  min_edge_weight: 0.1
  embedding_dim: 64
  max_walk_length: 10

logging:
  level: "INFO"
  file: "logs/quantum_system.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_file_size: 10485760  # 10MB
  backup_count: 5

paths:
  models: "models/"
  data: "data/"
  logs: "logs/"
  temp: "temp/"
  
analysis:
  molecular_descriptors:
    - "molecular_weight"
    - "rotatable_bonds"
    - "aromatic_rings"
    - "h_bond_donors"
    - "h_bond_acceptors"
  graph_metrics:
    - "clustering_coefficient"
    - "average_path_length"
    - "centrality"
